/*
 * Lee Li
 */

/**
 *
 * @author Lee Li
 */


public class DevelopingSoftwareforPlanetZirboin extends javax.swing.JFrame {

    int vrobit;
    int drobzit;
    int clickwick;
    int gazoontight;
    int frazoint;
    int blointoint;
    int userinput;
 
    public DevelopingSoftwareforPlanetZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltopic = new javax.swing.JLabel();
        lblPicture1 = new javax.swing.JLabel();
        lblDrobzit = new javax.swing.JLabel();
        lblClickwick = new javax.swing.JLabel();
        lblGazoontight = new javax.swing.JLabel();
        lblFrazoint = new javax.swing.JLabel();
        lblBlointoint = new javax.swing.JLabel();
        lblValueofDrobzit = new javax.swing.JLabel();
        lblValueofClickwick = new javax.swing.JLabel();
        lblValueofGazoontight = new javax.swing.JLabel();
        lblValueoffrazoint = new javax.swing.JLabel();
        lblValueofblointoint = new javax.swing.JLabel();
        txtCoin = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltopic.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbltopic.setForeground(new java.awt.Color(255, 0, 102));
        lbltopic.setText("New Galaxy Coin Conversion system");

        lblPicture1.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\Coin.jpg")); // NOI18N

        lblDrobzit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDrobzit.setForeground(new java.awt.Color(255, 0, 153));
        lblDrobzit.setText("Drobzit");

        lblClickwick.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblClickwick.setForeground(new java.awt.Color(51, 102, 255));
        lblClickwick.setText("Clickwick");

        lblGazoontight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGazoontight.setForeground(new java.awt.Color(255, 51, 51));
        lblGazoontight.setText("Gazoontight");

        lblFrazoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrazoint.setForeground(new java.awt.Color(255, 153, 102));
        lblFrazoint.setText("frazoint");

        lblBlointoint.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBlointoint.setForeground(new java.awt.Color(0, 153, 51));
        lblBlointoint.setText("blointoint ");

        lblValueofDrobzit.setForeground(new java.awt.Color(255, 0, 255));

        lblValueofClickwick.setForeground(new java.awt.Color(51, 51, 255));

        lblValueofGazoontight.setForeground(new java.awt.Color(255, 102, 102));

        lblValueoffrazoint.setForeground(new java.awt.Color(255, 153, 0));

        lblValueofblointoint.setForeground(new java.awt.Color(0, 153, 0));

        btnGo.setText("<(￣︶￣)↗[GO!]");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\The G AppareL Darius\\Downloads\\New Folder\\LLLL.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(btnGo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrobzit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGazoontight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFrazoint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblClickwick, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBlointoint, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValueofDrobzit)
                            .addComponent(lblValueofGazoontight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValueoffrazoint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValueofblointoint, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValueofClickwick, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPicture1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(lbltopic)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPicture1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltopic)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDrobzit)
                            .addComponent(lblValueofDrobzit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClickwick)
                            .addComponent(lblValueofClickwick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGazoontight)
                            .addComponent(lblValueofGazoontight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFrazoint)
                            .addComponent(lblValueoffrazoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlointoint)
                            .addComponent(lblValueofblointoint, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        
       userinput = Integer.parseInt(txtCoin.getText());  /* Making sure we can get the user Input*/
       
       if (userinput >= 100000)  /* Using if, else if system to determine the Value of coin*/
       {
           drobzit = userinput / 100000;  /* Value of Drobizt*/
           
           lblValueofDrobzit.setText(String.valueOf(drobzit));  /* Making the Value turn on the GUI*/
           
           clickwick = (userinput - (userinput / 100000)) / 50000;  /* Getting the value of Clickwick */
           
           lblValueofClickwick.setText(String.valueOf(clickwick));  /* Making the Value turn on the GUI*/
           
           gazoontight = (userinput - ((userinput - (userinput / 100000)) / 50000)) / 10000;  /* Getting the value of Gazoontight */ 
           
           lblValueofGazoontight.setText(String.valueOf(gazoontight));  /* Making the Value turn on the GUI*/
           
           frazoint = (userinput - (userinput - ((userinput - (userinput / 100000)) / 50000)) / 10000)/ 1000;  /* Getting the Value of Frazoint */
           
           lblValueoffrazoint.setText(String.valueOf(frazoint)); /* Making the Value turn on the GUI*/
           
           blointoint = (userinput - (userinput - ((userinput - (userinput / 100000)) / 50000)) / 10000)/ 500;  /* Getting the Value of Blointoint*/
           
           lblValueofblointoint.setText(String.valueOf(frazoint));  /* Making the Value turn on the GUI*/
         
       }
       else if (userinput >= 50000) 
       {
           clickwick = userinput / 50000;  /* Getting the New value of Clickwick */
           
           lblValueofClickwick.setText(String.valueOf(clickwick));  /* Making the New Value turn on the GUI*/
           
           gazoontight = userinput - (userinput / 50000) / 10000;  /* Getting the New Value of Gazoontight */ 
           
           lblValueofGazoontight.setText(String.valueOf(gazoontight));  /* Making the New Value turn on the GUI*/
           
           frazoint = userinput - (userinput - (userinput / 50000) / 10000 ) / 1000;  /* Getting the New Value of Frazoint */
           
           lblValueoffrazoint.setText(String.valueOf(frazoint)); /* Making the New Value turn on the GUI*/
           
           blointoint = userinput - (userinput - (userinput - (userinput / 50000) / 10000 ) / 1000) / 500;  /* Getting the New Value of Blointoint*/
           
           lblValueofblointoint.setText(String.valueOf(frazoint));  /* Making the New Value turn on the GUI*/ 
       }
       else if (userinput >= 10000)
       {
           gazoontight = userinput / 10000;  /* Getting the New Value of Gazoontight */ 
           
           lblValueofGazoontight.setText(String.valueOf(gazoontight));  /* Making the New Value turn on the GUI*/
           
           frazoint = userinput - (userinput / 10000) / 1000;  /* Getting the New Value of Frazoint */
           
           lblValueoffrazoint.setText(String.valueOf(frazoint)); /* Making the New Value turn on the GUI*/
           
           blointoint = userinput - (userinput - (userinput / 10000) / 1000) / 500;  /* Getting the New Value of Blointoint*/
           
           lblValueofblointoint.setText(String.valueOf(frazoint));  /* Making the New Value turn on the GUI*/ 
       }
       else if (userinput >= 1000)
       {
           frazoint = userinput / 1000;  /* Getting the New Value of Frazoint */
           
           lblValueoffrazoint.setText(String.valueOf(frazoint)); /* Making the New Value turn on the GUI*/
           
           blointoint = userinput - (userinput / 1000) / 500;  /* Getting the New Value of Blointoint*/
           
           lblValueofblointoint.setText(String.valueOf(frazoint));  /* Making the New Value turn on the GUI*/  
       }
        
    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareforPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevelopingSoftwareforPlanetZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBlointoint;
    private javax.swing.JLabel lblClickwick;
    private javax.swing.JLabel lblDrobzit;
    private javax.swing.JLabel lblFrazoint;
    private javax.swing.JLabel lblGazoontight;
    private javax.swing.JLabel lblPicture1;
    private javax.swing.JLabel lblValueofClickwick;
    private javax.swing.JLabel lblValueofDrobzit;
    private javax.swing.JLabel lblValueofGazoontight;
    private javax.swing.JLabel lblValueofblointoint;
    private javax.swing.JLabel lblValueoffrazoint;
    private javax.swing.JLabel lbltopic;
    private javax.swing.JTextField txtCoin;
    // End of variables declaration//GEN-END:variables
}
